name: Add SPDX headers

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.go'
      - '**/*.py'

jobs:
  addlicense:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sfL https://git.io/addlicense | bash -s -- -c "AGPL-3.0-only" -v 